name: CD

on:
  push:
    branches: [ main ]
    tags-ignore:
      - '*' # Ignore tags to avoid duplicate releases if sync.yml also creates them

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        id: get_version
        run: echo "VERSION=v$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: ${{ steps.get_version.outputs.VERSION }}
          body: |
            Automated release for version ${{ steps.get_version.outputs.VERSION }}
            Merged changes to main branch.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
